// 各グループの開始インデックスと項目名
export const COLUMN_MAP = {
  order: {
    workDays: 0,
    headcount: 1,
    manHours: 2,
    sales: 3,
    cost: 4,
    profit: 5,
    profitRate: 6,
  },
  actual: {
    workDays: 7,
    headcount: 8,
    manHours: 9,
    sales: 10,
    cost: 11,
    profit: 12,
    profitRate: 13,
  },
  gap: {
    workDays: 14,
    headcount: 15,
    manHours: 16,
    sales: 17,
    cost: 18,
    profit: 19,
    profitRate: 20,
  },
  recruitment: {
    recruitCount: 21,
    recruitCost: 22,
    applyCount: 23,
    applyCost: 24,
    interviewCount: 25,
    interviewCost: 26,
    hireCount: 27,
    hireCost: 28,
    hireRate: 29,
  },
  staffing: {
    dbCount: 30,
    activeCount: 31,
    avgTenureDays: 32,
    resignCount: 33,
    shortageCount: 34,
    absentCount: 35,
    dbUtilRate: 36,
    replacementDays: 37,
    recoveryDays: 38,
  },
  marketRate: {
    minWage: 39,
    areaRate: 40,
    avgHourlyWage: 41,
    gap: 42,
  },
  dailyAvg: {
    sales: 43,
    cost: 44,
    profit: 45,
    workHours: 46,
    fillRate: 47,
    attendanceRate: 48,
    utilRate: 49,
  },
  cumulative: {
    avgSales: 50,
    avgCost: 51,
    avgProfit: 52,
    avgWorkHours: 53,
    avgWorkDays: 54,
  },
} as const;